nginx:
    build: ./nginx-image
    links:
        - web1:web1
        - web2:web2
        - web3:web3
    ports:
        - "80:80"
web1:
    build: ./php-image
    links:
        - redis
    ports:
        - "80"
web2:
    build: ./php-image
    links:
        - redis
    ports:
        - "80"
web3:
    build: ./php-image
    links:
        - redis
    ports:
        - "80"
redis:
    image: redis
    ports:
        - "6379"



